In [1]:
from IPython.display import display, HTML 
display(HTML("""
<style>
div.container{width:86% !important;}
div.cell.code_cell.rendered{width:100%;}
div.CodeMirror {font-family:Consolas; font-size:15pt;}
div.output {font-size:15pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:15pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:15px;}
</style>
 """))

<span style="color:hotpink; font-size: 30px; font-weight: bold;"> ch10.N차원 배열다루기 </span>
- [numpy](https://numpy.org/doc/stable/)
- [numpy API](https://numpy.org/doc/stable/reference/index.html)
- N차원 배열 객체 만들기 위한 라이브러리
- 2차원 배열은 행렬개념으로 사용할 수 있음
- numpy는 c언어로 구현됨(속도가 빠름-고성능 수치 계산 패키지)

In [18]:
import numpy as np
a1 = np.array([[1,2,3],[4,5,6]])
print(a1)
print(a1.shape)
print(a1.ndim) # 넘파이 차원을 확인하는 방법 : ndim

a2 = np.arange(1,20,3) # array([ 1,  4,  7, 10, 13, 16, 19]) 1부터 20까지 3번씩 점프 
a3 = np.zeros((2,3))   # array([[0., 0., 0.], [0., 0., 0.]]) 2행 3열짜리 0
a4 = np.ones((3,2))    # array([[1., 1.],[1., 1.],[1., 1.]]) 3행 2열짜리 1
a5 = np.zeros_like(a4) # array([[0., 0.],[0., 0.],[0., 0.]]) 3행 2열짜리 0
a6 = np.full((2,3),9)  # array([[9 9 9] [9 9 9]]) 2열 3행짜리 9
a7 = np.random.random((3,2)) # array([[0.37372365, 0.0406329 ], [0.12775128, 0.97873443],[0.47114354, 0.79094854]])

#shape
a9 = np.arange(6).reshape(2,3) #array([[0, 1, 2], [3, 4, 5]]) 2행 3열 0부터 5까지 (6자리 나열) 
a10 = np.arange(6).reshape(-1,2) #array([[0,1],[2,3],[4,5]])
a11 = np.dot(a9, a10) # a
      
       
# 0*0 + 1*2 + 2*4 = 0 + 2 + 8 = 10   
# 0*1 + 1*3 + 2*5 = 0 + 3 + 10 = 13


[[1 2 3]
 [4 5 6]]
(2, 3)
2


array([[0, 1, 2],
       [3, 4, 5]])